### ISSUE TITLE
Merge in fork

### ISSUE THREAD

**Issue by rosshadden** [polachok/gtk-vikb#3]
@Watcom should make a PR for [his fork](https://github.com/Watcom/gtk-vikb).  I'm currently using his fork, which adds some new features, and it works great.

Also this project is amazing!  After so many years of settling for mere basic vi mappings in gtk apps, I had long given up hope of anything better.

**Comment by polachok** [comment]
If he does, I'll be happy to merge it and add him as maintainer.

**Comment by Watcom** [comment]
Sorry, I thought nobody used it anymore. I must agree with @rosshadden, it is indeed amazing.

**Comment by oz123** [comment]
Does this also work with gtk3?

**Comment by rosshadden** [comment]
No.
